// src/app/layout.tsx
import React from 'react'
import Head from 'next/head'
import "./globals.css";
import { ReactNode } from 'react'
import type { Metadata } from "next";
import Navbar from '@/components/Navbar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body>
        <header><Navbar /></header>
        <main>{children}</main>
        <footer>
          <p>&copy; 2025 My Anime Tracker</p>
        </footer>
      </body>
    </html>
  )
}


/**
 * 
export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
    <body
    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    {children}
    </body>
    </html>
  );
}
*/