// src/animeListData.js

export const AnimeListData = {
  currentlyWatching: [
    {
      id: 1,
      title: "Attack on Titan",
      description: "Humans fight against titans to survive.",
      image: "https://placehold.co/120x160.png?text=Attack+on+Titan",
      rating: 9.0,
      seasons: 4,
      totalEpisodes: 87,
      currentSeason: 4,
      watchedEpisodes: 45,
      genres: ["Action", "Drama", "Fantasy"],
    },
    {
      id: 2,
      title: "Demon Slayer",
      description: "A boy fights demons to save his sister.",
      image: "https://placehold.co/120x160.png?text=Demon+Slayer",
      rating: 8.8,
      seasons: 3,
      totalEpisodes: 44,
      currentSeason: 3,
      watchedEpisodes: 12,
      genres: ["Action", "Adventure", "Fantasy"],
    },
  ],
  watched: [
    {
      id: 3,
      title: "Death Note",
      description: "A high school student gains a notebook that kills.",
      image: "https://placehold.co/120x160.png?text=Death+Note",
      rating: 9.2,
      seasons: 1,
      totalEpisodes: 37,
      currentSeason: 1,
      watchedEpisodes: 37,
      genres: ["Mystery", "Thriller", "Supernatural"],
    },
    {
      id: 4,
      title: "Code Geass",
      description: "A young man fights against a tyrannical empire.",
      image: "https://placehold.co/120x160.png?text=Code+Geass",
      rating: 8.9,
      seasons: 2,
      totalEpisodes: 50,
      currentSeason: 2,
      watchedEpisodes: 50,
      genres: ["Action", "Mecha", "Drama"],
    },
    {
      id: 5,
      title: "Fullmetal Alchemist: Brotherhood",
      description: "Alchemy, adventure, and a journey for the truth.",
      image: "https://placehold.co/120x160.png?text=FMA",
      rating: 9.5,
      seasons: 1,
      totalEpisodes: 64,
      currentSeason: 1,
      watchedEpisodes: 64,
      genres: ["Action", "Fantasy", "Adventure"],
    },
    {
      id: 6,
      title: "Steins;Gate",
      description: "Time travel experiments with unpredictable consequences.",
      image: "https://placehold.co/120x160.png?text=SteinsGate",
      rating: 9.1,
      seasons: 1,
      totalEpisodes: 24,
      currentSeason: 1,
      watchedEpisodes: 24,
      genres: ["Sci-Fi", "Thriller", "Drama"],
    },
  ],
  toWatch: [
    {
      id: 7,
      title: "Tokyo Revengers",
      description: "A man travels back in time to save his friends.",
      image: "https://placehold.co/120x160.png?text=Tokyo+Revengers",
      rating: 8.1,
      seasons: 1,
      totalEpisodes: 24,
      currentSeason: 1,
      watchedEpisodes: 0,
      genres: ["Action", "Drama", "School"],
    },
    {
      id: 8,
      title: "Jujutsu Kaisen",
      description: "A boy battles curses with powerful jujutsu techniques.",
      image: "https://placehold.co/120x160.png?text=Jujutsu+Kaisen",
      rating: 8.7,
      seasons: 2,
      totalEpisodes: 39,
      currentSeason: 2,
      watchedEpisodes: 0,
      genres: ["Action", "Fantasy", "Supernatural"],
    },
    {
      id: 9,
      title: "Parasyte",
      description: "A teenager fights alien parasites taking over humans.",
      image: "https://placehold.co/120x160.png?text=Parasyte",
      rating: 8.5,
      seasons: 1,
      totalEpisodes: 24,
      currentSeason: 1,
      watchedEpisodes: 0,
      genres: ["Horror", "Sci-Fi", "Thriller"],
    },
    {
      id: 10,
      title: "Kakegurui",
      description: "Students gamble at an elite academy where stakes are high.",
      image: "https://placehold.co/120x160.png?text=Kakegurui",
      rating: 8.0,
      seasons: 1,
      totalEpisodes: 12,
      currentSeason: 1,
      watchedEpisodes: 0,
      genres: ["Psychological", "Drama", "School"],
    },
    {
      id: 11,
      title: "My Hero Academia",
      description: "Young heroes-in-training fight villains in a superpowered world.",
      image: "https://placehold.co/120x160.png?text=My+Hero+Academia",
      rating: 8.5,
      seasons: 5,
      totalEpisodes: 113,
      currentSeason: 1,
      watchedEpisodes: 0,
      genres: ["Action", "Adventure", "Superhero"],
    },
    {
      id: 12,
      title: "Sword Art Online",
      description: "Players are trapped in a deadly virtual reality game.",
      image: "https://placehold.co/120x160.png?text=SAO",
      rating: 8.3,
      seasons: 3,
      totalEpisodes: 96,
      currentSeason: 1,
      watchedEpisodes: 0,
      genres: ["Action", "Adventure", "Fantasy"],
    },
    {
      id: 13,
      title: "Vinland Saga",
      description: "Viking revenge and conquest in historical times.",
      image: "https://placehold.co/120x160.png?text=Vinland+Saga",
      rating: 8.8,
      seasons: 2,
      totalEpisodes: 48,
      currentSeason: 1,
      watchedEpisodes: 0,
      genres: ["Action", "Drama", "History"],
    },
    {
      id: 14,
      title: "Spy X Family",
      description: "A spy, an assassin, and a telepath form a fake family.",
      image: "https://placehold.co/120x160.png?text=Spy+X+Family",
      rating: 8.9,
      seasons: 1,
      totalEpisodes: 25,
      currentSeason: 1,
      watchedEpisodes: 0,
      genres: ["Action", "Comedy", "Slice of Life"],
    },
    {
      id: 15,
      title: "Rent a Girlfriend",
      description: "A boy rents a girlfriend to cope with his breakup.",
      image: "https://placehold.co/120x160.png?text=Rent+a+Girlfriend",
      rating: 7.8,
      seasons: 2,
      totalEpisodes: 24,
      currentSeason: 1,
      watchedEpisodes: 0,
      genres: ["Romance", "Comedy", "Drama"],
    },
  ],
};